name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
      - run: docker build -t iatul/multi-client ./client
      - run: docker build -t iatul/multi-server ./server
      - run: docker build -t iatul/multi-worker ./worker
      - run: docker build -t iatul/multi-nginx ./nginx

      - run: docker push iatul/multi-client
      - run: docker push iatul/multi-server
      - run: docker push iatul/multi-worker
      - run: docker push iatul/multi-nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-382862041657
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip