name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t atul-kumar/react-test -f ./client/Dockerfile.dev .
      
      - run: docker build -t atul-kumar/multi-client ./client
      - run: docker build -t atul-kumar/multi-server ./server
      - run: docker build -t atul-kumar/multi-worker ./worker
      - run: docker build -t atul-kumar/multi-nginx ./nginx

      - run: docker push atul-kumar/multi-client
      - run: docker push atul-kumar/multi-server
      - run: docker push atul-kumar/multi-worker
      - run: docker push atul-kumar/multi-nginx